In [8]:
def convert_units(conversion_type, value):
    """
    Converts a value between different units.

    Parameters:
    conversion_type (int): The type of conversion to perform.
    value (float): The value to be converted.
    """

    if conversion_type == 1:  # meters to feet
        return value * 3.28084
    elif conversion_type == 2:  # feet to meters
        return value / 3.28084
    elif conversion_type == 3:  # kilograms to pounds
        return value * 2.20462
    elif conversion_type == 4:  # pounds to kilograms
        return value / 2.20462
    elif conversion_type == 5:  # liters to gallons
        return value * 0.264172
    elif conversion_type == 6:  # gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Converter")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Choose conversion type (1-6): "))

        if choice < 1 or choice > 6:
            print("Unsupported conversion type.")
            return

        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is not None:
            print("Converted value:", round(result, 3))
        else:
            print("Conversion failed.")

    except ValueError:
        print("Invalid input! Please enter numeric values.")


# Run the program
main()

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 4
Enter the value to convert: 13
Converted value: 5.897


In [9]:
# Function to calculate sum
def find_sum(numbers):
    """
    Returns the sum of a list of numbers.

    """
    return sum(numbers)


# Function to calculate average
def find_average(numbers):
    """
    Returns the average of a list of numbers.

    """
    return sum(numbers) / len(numbers)


# Function to find maximum
def find_maximum(numbers):
    """
    Returns the maximum value from a list of numbers.

    """
    return max(numbers)


# Function to find minimum
def find_minimum(numbers):
    """
    Returns the minimum value from a list of numbers.

    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))

        numbers_input = input("Enter numbers separated by spaces: ")
        numbers = [float(num) for num in numbers_input.split()]

        if len(numbers) == 0:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            print("Sum:", find_sum(numbers))
        elif choice == 2:
            print("Average:", find_average(numbers))
        elif choice == 3:
            print("Maximum:", find_maximum(numbers))
        elif choice == 4:
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


# Run program
main()

Mathematical Operations on a List
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Choose an operation (1-4): 2
Enter numbers separated by spaces: 12 45 57
Average: 38.0


In [10]:
#  Problem - 1: Array Creation
print("=== Problem 1: Array Creation ===")
import numpy as np


# Task 1: Empty 2x2 array
empty_arr = np.empty((2, 2))
print("1. Empty 2x2:\n", empty_arr)

# Task 2: All ones 4x2
ones_4x2 = np.ones((4, 2))
print("\n2. All ones 4x2:\n", ones_4x2)

# Task 3: np.full example (shape 3x3, fill value 7)
full_arr = np.full((3, 3), 7)
print("\n3. np.full(3x3, 7):\n", full_arr)

# Task 4: zeros_like
sample = np.array([[1, 2], [3, 4]])
zeros_like = np.zeros_like(sample)
print("\n4. zeros_like:\n", zeros_like)

# Task 5: ones_like
ones_like = np.ones_like(sample)
print("\n5. ones_like:\n", ones_like)

# Task 6: List to numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\n6. From list:", arr_from_list)

=== Problem 1: Array Creation ===
1. Empty 2x2:
 [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]

2. All ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. np.full(3x3, 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like:
 [[0 0]
 [0 0]]

5. ones_like:
 [[1 1]
 [1 1]]

6. From list: [1 2 3 4]


In [11]:
# Problem - 2: Array Manipulation
print("=== Problem 2: Array Manipulation ===")

# Task 1: 10 to 49
range_arr = np.arange(10, 50)
print("1. 10 to 49:\n", range_arr)

# Task 2: 3x3 matrix 0-8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 0-8:\n", matrix_3x3)

# Task 3: Identity 3x3
identity = np.eye(3)
print("\n3. Identity 3x3:\n", identity)

# Task 4: Random 30 + mean
rand30 = np.random.random(30)
print("\n4. Random 30 mean:", rand30.mean())

# Task 5: 10x10 random min/max
rand10x10 = np.random.random((10, 10))
print("\n5. 10x10 min:", rand10x10.min(), "max:", rand10x10.max())

# Task 6: Zero array, replace 5th element (index 4)
zero10 = np.zeros(10)
zero10[4] = 1
print("\n6. Zero10 with 5th=1:", zero10)

# Task 7: Reverse
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed:", reversed_arr)

# Task 8: 2D border 1 inside 0 (5x5 example)
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n8. Border 1 inside 0:\n", border)

# Task 9: 8x8 checkerboard
checker = np.zeros((8, 8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\n9. Checkerboard 8x8:\n", checker)

=== Problem 2: Array Manipulation ===
1. 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random 30 mean: 0.557292673190813

5. 10x10 min: 0.004216708457077223 max: 0.9999559421019827

6. Zero10 with 5th=1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed: [0 4 0 0 2 1]

8. Border 1 inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
# Problem - 3: Array Operations
print("=== Problem 3: Array Operations ===")

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add
print("1. x + y:\n", x + y)

# Task 2: Subtract
print("\n2. x - y:\n", x - y)

# Task 3: Multiply by 2
print("\n3. x * 2:\n", x * 2)

# Task 4: Square
print("\n4. x ** 2:\n", x ** 2)

# Task 5: Dot products
print("\n5. v·w =", np.dot(v, w))
print("   x·v =", np.dot(x, v))
print("   x·y =", np.dot(x, y))

# Task 6: Concatenate
row_concat = np.concatenate((x, y), axis=0)   # or np.vstack
col_concat = np.concatenate((v.reshape(2,1), w.reshape(2,1)), axis=1)
print("\n6. x&y row concat:\n", row_concat)
print("   v&w column concat:\n", col_concat)

# Task 7: Concat x and v → Error explanation
try:
    np.concatenate((x, v))
except ValueError as e:
    print("\n7. Error when concat x and v:", str(e))
    print("   Reason: x is 2x2, v is 1D (shape mismatch). Need reshape or different axis.")

=== Problem 3: Array Operations ===
1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 2:
 [[ 2  4]
 [ 6 10]]

4. x ** 2:
 [[ 1  4]
 [ 9 25]]

5. v·w = 219
   x·v = [29 77]
   x·y = [[19 22]
 [50 58]]

6. x&y row concat:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   v&w column concat:
 [[ 9 11]
 [10 12]]

7. Error when concat x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Reason: x is 2x2, v is 1D (shape mismatch). Need reshape or different axis.


In [14]:
#  Problem - 4: Matrix Operations + Linear Equations
print("=== Problem 4: Matrix Operations ===")

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. A * A_inv = I
A_inv = np.linalg.inv(A)
print("1. A @ A_inv:\n", np.round(A @ A_inv, decimals=10))
print("   (Should be Identity)")

# 2. AB ≠ BA
AB = A @ B
BA = B @ A
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))

# 3. (AB)^T == B^T @ A^T
print("\n3. (AB).T:\n", AB.T)
print("   B.T @ A.T:\n", B.T @ A.T)
print("   Equal?", np.array_equal(AB.T, B.T @ A.T))

# Linear Equation System
print("\n=== Solving Linear System ===")
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])
const = np.array([-1, -3, 9])

# Using inverse
inv_coeff = np.linalg.inv(coeff)
solution = inv_coeff @ const
print("Solution using np.linalg.inv:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])

# Bonus: Using np.linalg.solve (faster & recommended)
solution2 = np.linalg.solve(coeff, const)
print("\nSame solution with np.linalg.solve:", solution2)


=== Problem 4: Matrix Operations ===
1. A @ A_inv:
 [[1. 0.]
 [0. 1.]]
   (Should be Identity)

2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB == BA? False

3. (AB).T:
 [[23 51]
 [13 29]]
   B.T @ A.T:
 [[23 51]
 [13 29]]
   Equal? True

=== Solving Linear System ===
Solution using np.linalg.inv:
x = 2.0
y = 1.0
z = -2.0

Same solution with np.linalg.solve: [ 2.  1. -2.]
